---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  template:
    spec:
      containers:
      - name: webserver-simple
        env:
        - name: ENV
          value: "qa"
        - name: GPU_ENABLED
          value: "0"
 ---         
apiVersion: v1
kind: Namespace
metadata:
  name: qa
  labels:
    name: qa
