---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  template:
    spec:
      containers:
      - name: webserver-simple
        env:
        - name: ENV
          value: "prod"
        - name: GPU_ENABLED
          value: "1"
---         
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    name: prod
